apiVersion: apim.googleapis.com/v1alpha1
kind: APIProduct
metadata:
 name: broker-product
 namespace: apigee
spec:
  name: broker-product
  approvalType: auto
  description: broker-product provides publication capabilities.
  displayName: Broker
  analytics:
    enabled: true
  enforcementRefs:
  - name: global-ext-lb1-apim-policy 
    kind: APIMExtensionPolicy
    group: apim.googleapis.com
    namespace: apigee
  attributes:
  - name: access
    value: public

